//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JacquelineJasminRoblesGaldamez.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int idNota { get; set; }
        public Nullable<int> idMateria { get; set; }
        public Nullable<int> idEstudiante { get; set; }
        public Nullable<double> Nota { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
